# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flare',
            name='priority',
            field=models.IntegerField(choices=[(1, 'LOW'), (2, 'MEDIUM'), (3, 'HIGH'), (4, 'EXTREME')], default=1),
        ),
    ]
