# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 02:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_flare_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flare',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
